version: "3"
services:
  server:
    image: servauto/server
    build:
      dockerfile: server.dockerfile
      context: .
    hostname: server.servauto.com
    ports:
      - "8000:8000"
    networks:
      - servauto-network
  tests:
    image: servauto/tests
    build:
      dockerfile: tests.dockerfile
      context: .
    depends_on:
      - server
    networks:
      - servauto-network
networks:
  servauto-network: